name 'youdiyuan'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures listserv'
long_description 'Installs/Configures listserv'
version '0.1.0'
depends 'postfix'
depends 'apache2'
depends 'mailman'
